In [38]:
#Load library yang akan digunakan
#sklearn.svm import SVR digunakan untuk mengimport class library untuk svr
import pandas as pd
from openpyxl import load_workbook
from sklearn import preprocessing as pre
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

In [40]:
#Mengatur nama file csv yang digunakan
df = pd.read_csv('data.csv')
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [41]:
#inisialisasi atau pendefinisian varieble dengan nama kolom
df.columns = ['date', 'price', 'bdroom', 'bathroom', 'sqft_living', 'sqt_lot', 'floors', 'waterfront', 'view', 'condition', 'sqt_above', 'sqt_basement', 'yr_build', 'yr_renovate', 'street', 'city', 'statezip', 'country']
df

date         price  bdroom  bathroom  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05     3.0      1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06     5.0      2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05     3.0      2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05     3.0      2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05     4.0      2.50         1940   
...                   ...           ...     ...       ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05     3.0      1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05     3.0      2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05     3.0      2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05     4.0      2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05     3.0      2.50         1490   

      sqt_lot  floors  waterfront  view  condition  sqt_above  sqt_basement  \
0        7912     1.5           0     0          3       1340             0   
1        9050     2.0           0     4          5       3370           280   
2       11947     1.0           0     0          4       1930             0   
3        8030     1.0           0     0          4       1000          1000   
4       10500     1.0           0     0          4       1140           800   
...       ...     ...         ...   ...        ...        ...           ...   
4595     6360     1.0           0     0          4       1510             0   
4596     7573     2.0           0     0          3       1460             0   
4597     7014     2.0           0     0          3       3010             0   
4598     6630     1.0           0     0          3       1070          1020   
4599     8102     2.0           0     0          4       1490             0   

      yr_build  yr_renovate                    street       city  statezip  \
0         1955         2005      18810 Densmore Ave N  Shoreline  WA 98133   
1         1921            0           709 W Blaine St    Seattle  WA 98119   
2         1966            0  26206-26214 143rd Ave SE       Kent  WA 98042   
3         1963            0           857 170th Pl NE   Bellevue  WA 98008   
4         1976         1992         9105 170th Ave NE    Redmond  WA 98052   
...        ...          ...                       ...        ...       ...   
4595      1954         1979            501 N 143rd St    Seattle  WA 98133   
4596      1983         2009          14855 SE 10th Pl   Bellevue  WA 98007   
4597      2009            0          759 Ilwaco Pl NE     Renton  WA 98059   
4598      1974            0         5148 S Creston St    Seattle  WA 98178   
4599      1990            0         18717 SE 258th St  Covington  WA 98042   

     country  
0        USA  
1        USA  
2        USA  
3        USA  
4        USA  
...      ...  
4595     USA  
4596     USA  
4597     USA  
4598     USA  
4599     USA  

[4600 rows x 18 columns]

In [42]:
#checking tipe data
print(df.dtypes)

date             object
price           float64
bdroom          float64
bathroom        float64
sqft_living       int64
sqt_lot           int64
floors          float64
waterfront        int64
view              int64
condition         int64
sqt_above         int64
sqt_basement      int64
yr_build          int64
yr_renovate       int64
street           object
city             object
statezip         object
country          object
dtype: object


In [43]:
#Ubah index data frame agar lebih memudahkan dalam melakukan forecasting
d_train = df [['date', 'price', 'bdroom', 'bathroom', 'sqft_living', 'sqt_lot', 'floors', 'waterfront', 'view', 'condition', 'sqt_above', 'sqt_basement', 'yr_build', 'yr_renovate']].reset_index(drop = True)
d_train

date         price  bdroom  bathroom  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05     3.0      1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06     5.0      2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05     3.0      2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05     3.0      2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05     4.0      2.50         1940   
...                   ...           ...     ...       ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05     3.0      1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05     3.0      2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05     3.0      2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05     4.0      2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05     3.0      2.50         1490   

      sqt_lot  floors  waterfront  view  condition  sqt_above  sqt_basement  \
0        7912     1.5           0     0          3       1340             0   
1        9050     2.0           0     4          5       3370           280   
2       11947     1.0           0     0          4       1930             0   
3        8030     1.0           0     0          4       1000          1000   
4       10500     1.0           0     0          4       1140           800   
...       ...     ...         ...   ...        ...        ...           ...   
4595     6360     1.0           0     0          4       1510             0   
4596     7573     2.0           0     0          3       1460             0   
4597     7014     2.0           0     0          3       3010             0   
4598     6630     1.0           0     0          3       1070          1020   
4599     8102     2.0           0     0          4       1490             0   

      yr_build  yr_renovate  
0         1955         2005  
1         1921            0  
2         1966            0  
3         1963            0  
4         1976         1992  
...        ...          ...  
4595      1954         1979  
4596      1983         2009  
4597      2009            0  
4598      1974            0  
4599      1990            0  

[4600 rows x 14 columns]

In [53]:
#Menentukan kolom yang digunakan sebagai class target forcasting
#Kolom yang digunakan adalah price
y = targets = labels = d_train['price'].apply(float).values
y


array([ 313000.      , 2384000.      ,  342000.      , ...,
        416904.166667,  203400.      ,  220600.      ])

In [67]:
#Menentukan kolom yang digunakan sebagai fitur-fitur
columns = ['bdroom', 'bathroom', 'sqft_living', 'sqt_lot', 'floors', 'waterfront', 'view', 'condition', 'sqt_above', 'sqt_basement', 'yr_build', 'yr_renovate']
features = d_train[list(columns)].values
features

array([[3.000e+00, 1.500e+00, 1.340e+03, ..., 0.000e+00, 1.955e+03,
        2.005e+03],
       [5.000e+00, 2.500e+00, 3.650e+03, ..., 2.800e+02, 1.921e+03,
        0.000e+00],
       [3.000e+00, 2.000e+00, 1.930e+03, ..., 0.000e+00, 1.966e+03,
        0.000e+00],
       ...,
       [3.000e+00, 2.500e+00, 3.010e+03, ..., 0.000e+00, 2.009e+03,
        0.000e+00],
       [4.000e+00, 2.000e+00, 2.090e+03, ..., 1.020e+03, 1.974e+03,
        0.000e+00],
       [3.000e+00, 2.500e+00, 1.490e+03, ..., 0.000e+00, 1.990e+03,
        0.000e+00]])

In [68]:
#Menyiapkan data feature untuk proses training
scaler = pre.StandardScaler().fit(features)
X = scaler.transform(features)
X

array([[-0.44112227, -0.84320364, -0.82997105, ..., -0.67246372,
        -0.53101376,  1.22167046],
       [ 1.75970468,  0.43280154,  1.56852826, ..., -0.06912828,
        -1.67469295, -0.82569345],
       [-0.44112227, -0.20520105, -0.21736733, ..., -0.67246372,
        -0.1609999 , -0.82569345],
       ...,
       [-0.44112227,  0.43280154,  0.90400897, ..., -0.67246372,
         1.2854179 , -0.82569345],
       [ 0.6592912 , -0.20520105, -0.05123751, ...,  1.5254011 ,
         0.10810108, -0.82569345],
       [-0.44112227,  0.43280154, -0.67422434, ..., -0.67246372,
         0.64630305, -0.82569345]])

In [69]:
SVR_model = SVR(kernel = 'linear' , C = 100, gamma = 'auto').fit(X, y)
SVR_model

SVR(C=100, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [70]:
#Menggunakan 100 data sample yang diambil secara random
d_test = d_train.sample(n = 100)
d_test

date      price  bdroom  bathroom  sqft_living  sqt_lot  \
305   2014-05-07 00:00:00   375000.0     3.0      2.50         1830    13042   
601   2014-05-13 00:00:00   635000.0     4.0      1.75         1950    13320   
2607  2014-06-16 00:00:00  1920000.0     4.0      2.50         3070    34412   
3414  2014-06-26 00:00:00   415000.0     3.0      1.00         1170     6700   
695   2014-05-14 00:00:00   707000.0     4.0      3.25         3200     7081   
...                   ...        ...     ...       ...          ...      ...   
2906  2014-06-19 00:00:00  1027000.0     3.0      2.50         2430    10500   
2422  2014-06-12 00:00:00   656500.0     4.0      2.00         2710     4750   
270   2014-05-07 00:00:00   492000.0     4.0      2.50         3305    16164   
3299  2014-06-25 00:00:00   905000.0     5.0      3.50         3100    10200   
3163  2014-06-23 00:00:00   515000.0     5.0      3.25         2910     5027   

      floors  waterfront  view  condition  sqt_above  sqt_basement  yr_build  \
305      2.0           0     0          3       1830             0      1990   
601      1.0           0     0          4       1370           580      1969   
2607     1.0           0     3          4       2070          1000      1950   
3414     1.0           0     0          3       1170             0      1957   
695      2.0           0     0          3       3200             0      2004   
...      ...         ...   ...        ...        ...           ...       ...   
2906     2.0           0     1          3       2430             0      1989   
2422     1.0           0     0          4       1460          1250      1919   
270      1.5           0     0          5       2245          1060      1922   
3299     1.0           0     4          3       1660          1440      1970   
3163     2.0           0     0          3       2040           870      2013   

      yr_renovate  
305          2009  
601             0  
2607         1983  
3414         2000  
695          2003  
...           ...  
2906            0  
2422         1985  
270          1956  
3299         2014  
3163         1923  

[100 rows x 14 columns]

In [78]:
#Menentukan kolom sebagai kelas target atau label pada data uji
columns = ['bdroom', 'bathroom', 'sqft_living', 'sqt_lot', 'floors', 'waterfront', 'view', 'condition', 'sqt_above', 'sqt_basement', 'yr_build', 'yr_renovate']
features_test = d_test[list(columns)].values

In [79]:
#Menentukan kolom yang digunakan untuk feature pada data uji
y_true = d_test['price'].values
y_true

array([ 375000.      ,  635000.      , 1920000.      ,  415000.      ,
        707000.      ,  210000.      ,  442500.      ,  622500.      ,
        325000.      ,  229950.      ,  561000.      ,  402500.      ,
        329350.      , 1054690.      ,  202000.      ,  603500.      ,
        430000.      ,  570000.      ,  630000.      ,  499500.      ,
        725000.      ,  291000.      ,  560000.      ,  225000.      ,
       1300000.      , 1339000.      ,  425000.      ,  682000.      ,
        250000.      ,  425000.      ,       0.      ,  457500.      ,
        455000.      ,  760000.      ,  294999.      ,  409316.      ,
        260000.      ,  240000.      ,  401000.      , 1555000.      ,
        300000.      ,  511555.      ,  356000.      , 2700000.      ,
        148000.      ,  755000.      ,  309000.      ,  830000.      ,
        185000.      ,  440000.      ,  425000.      ,  530000.      ,
        604000.      ,  625000.      ,  270000.      ,  625000.      ,
      

In [80]:
#Menyiapkan data untuk proses testing
scaler_test = pre.StandardScaler().fit(features_test)
testdata = scaler_test.transform(features_test)

In [81]:
#Prediksi house price 
predict = SVR_model.predict(testdata)
predict

array([ 470331.6734806 ,  420953.08971938,  729703.34420317,
        292107.62965396,  673765.45418014,  449885.79397986,
        501623.15104967,  604496.03984371,  486130.78117447,
        339530.786475  ,  569650.3022583 ,  284523.1872238 ,
        251699.83505499,  686888.15139258,  275038.42156941,
        845640.81283761,  864508.48859352,  419909.98938827,
        511125.29526195,  534088.57399065,  561984.43289109,
        371387.25031   ,  398515.4321665 ,  379000.62479724,
        739193.61713759,  886963.63737801,  537969.3497349 ,
        599369.32310616,  433900.96398273,  348944.4498717 ,
        604936.29077206,  480182.06438818,  462105.35241226,
        650802.50096765,  429263.36091655,  428983.22259584,
        447298.48537008,  363970.33825377,  303963.55790184,
        920688.37345916,  322857.40030788,  370511.22489708,
        289725.232653  , 1072755.02796865,  244890.79049298,
        568467.85568542,  378615.5240822 ,  615137.98212588,
        309838.35355908,

In [82]:
#Nilai Mean Absolute Precentage Error
import numpy as np

def mean_absolute_percentage_error(y_true, predict):
    y_true, predict = np.array(y_true), np.array(predict)
    return np.mean(np.abs((y_true - predict)) * 100)

mean_absolute_percentage_error(y_true, predict)

19438556.60441238

In [83]:
#Nilai Mean Squared Error
from sklearn.metrics import mean_squared_error
y_true_mse = d_test['price'].values
y_true_mse

array([ 375000.      ,  635000.      , 1920000.      ,  415000.      ,
        707000.      ,  210000.      ,  442500.      ,  622500.      ,
        325000.      ,  229950.      ,  561000.      ,  402500.      ,
        329350.      , 1054690.      ,  202000.      ,  603500.      ,
        430000.      ,  570000.      ,  630000.      ,  499500.      ,
        725000.      ,  291000.      ,  560000.      ,  225000.      ,
       1300000.      , 1339000.      ,  425000.      ,  682000.      ,
        250000.      ,  425000.      ,       0.      ,  457500.      ,
        455000.      ,  760000.      ,  294999.      ,  409316.      ,
        260000.      ,  240000.      ,  401000.      , 1555000.      ,
        300000.      ,  511555.      ,  356000.      , 2700000.      ,
        148000.      ,  755000.      ,  309000.      ,  830000.      ,
        185000.      ,  440000.      ,  425000.      ,  530000.      ,
        604000.      ,  625000.      ,  270000.      ,  625000.      ,
      

In [84]:
#Nilai Man Absolute Deviation
mean_absolute_error(y_true, predict)

194385.56604412384